/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const flagUpdateRequest: core.schemas.ObjectSchema<flagUpdateRequest.Raw, FliptApi.flags.flagUpdateRequest> =
  core.schemas.object({
    name: core.schemas.string(),
    description: core.schemas.string().optional(),
    enabled: core.schemas.boolean().optional(),
  });

export declare namespace flagUpdateRequest {
  interface Raw {
    name: string;
    description?: string | null;
    enabled?: boolean | null;
  }
}
