/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const flagList: core.schemas.ObjectSchema<flagList.Raw, FliptApi.flags.flagList> = core.schemas
  .object({
    flags: core.schemas.list(core.schemas.lazyObject(() => serializers.flags.flag)),
  })
  .extend(core.schemas.lazyObject(() => serializers.commons.Pageable));

export declare namespace flagList {
  interface Raw extends serializers.commons.Pageable.Raw {
    flags: serializers.flags.flag.Raw[];
  }
}
