/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const flagCreateRequest: core.schemas.ObjectSchema<flagCreateRequest.Raw, FliptApi.flags.flagCreateRequest> =
  core.schemas.object({
    key: core.schemas.string(),
    name: core.schemas.string(),
    description: core.schemas.string().optional(),
    enabled: core.schemas.boolean().optional(),
  });

export declare namespace flagCreateRequest {
  interface Raw {
    key: string;
    name: string;
    description?: string | null;
    enabled?: boolean | null;
  }
}
