/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const Flag: core.schemas.ObjectSchema<Flag.Raw, FliptApi.Flag> = core.schemas.object({
  key: core.schemas.string(),
  name: core.schemas.string(),
  description: core.schemas.string(),
  enabled: core.schemas.boolean(),
  createdAt: core.schemas.date(),
  updatedAt: core.schemas.date(),
  variants: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Variant)),
});

export declare namespace Flag {
  interface Raw {
    key: string;
    name: string;
    description: string;
    enabled: boolean;
    createdAt: string;
    updatedAt: string;
    variants: serializers.Variant.Raw[];
  }
}
