/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const FlagCreateRequest: core.schemas.ObjectSchema<FlagCreateRequest.Raw, FliptApi.FlagCreateRequest> =
  core.schemas.object({
    key: core.schemas.string(),
    name: core.schemas.string(),
    description: core.schemas.string().optional(),
    enabled: core.schemas.boolean().optional(),
  });

export declare namespace FlagCreateRequest {
  interface Raw {
    key: string;
    name: string;
    description?: string | null;
    enabled?: boolean | null;
  }
}
