/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const flag: core.schemas.ObjectSchema<flag.Raw, FliptApi.flags.flag> = core.schemas.object({
  key: core.schemas.string(),
  name: core.schemas.string(),
  description: core.schemas.string(),
  enabled: core.schemas.boolean(),
  createdAt: core.schemas.date(),
  updatedAt: core.schemas.date(),
  variants: core.schemas.list(core.schemas.lazyObject(() => serializers.variants.variant)),
});

export declare namespace flag {
  interface Raw {
    key: string;
    name: string;
    description: string;
    enabled: boolean;
    createdAt: string;
    updatedAt: string;
    variants: serializers.variants.variant.Raw[];
  }
}
