/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptCreateFlagRequest: core.schemas.ObjectSchema<
  fliptCreateFlagRequest.Raw,
  FliptApi.flags.fliptCreateFlagRequest
> = core.schemas.object({
  key: core.schemas.string(),
  name: core.schemas.string(),
  description: core.schemas.string().optional(),
  enabled: core.schemas.boolean().optional(),
});

export declare namespace fliptCreateFlagRequest {
  interface Raw {
    key: string;
    name: string;
    description?: string | null;
    enabled?: boolean | null;
  }
}
