/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptFlagList: core.schemas.ObjectSchema<fliptFlagList.Raw, FliptApi.flags.fliptFlagList> = core.schemas
  .object({
    flags: core.schemas.list(core.schemas.lazyObject(() => serializers.flags.fliptFlag)),
  })
  .extend(core.schemas.lazyObject(() => serializers.commons.Pageable));

export declare namespace fliptFlagList {
  interface Raw extends serializers.commons.Pageable.Raw {
    flags: serializers.flags.fliptFlag.Raw[];
  }
}
