/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.rules.get.Response.Raw, FliptApi.Rule> = core.schemas.lazyObject(
  async () => (await import("../..")).Rule
);

export declare namespace Response {
  type Raw = serializers.Rule.Raw;
}
