/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.rules.list.Response.Raw, FliptApi.RuleList> =
  core.schemas.lazyObject(async () => (await import("../..")).RuleList);

export declare namespace Response {
  type Raw = serializers.RuleList.Raw;
}
