/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.rules.order.Request.Raw, FliptApi.RuleOrder> =
  core.schemas.object({
    ruleIds: core.schemas.list(core.schemas.string()),
  });

export declare namespace Request {
  interface Raw {
    ruleIds: string[];
  }
}
