/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.rules.update.Request.Raw, FliptApi.RuleUpdateRequest> =
  core.schemas.object({
    segmentKey: core.schemas.string(),
  });

export declare namespace Request {
  interface Raw {
    segmentKey: string;
  }
}
