/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VariantCreateRequest {
    key: string;
    name?: string;
    description?: string;
    attachment?: string;
}
