/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptRuleList: core.schemas.ObjectSchema<fliptRuleList.Raw, FliptApi.rules.fliptRuleList> =
  core.schemas.object({
    rules: core.schemas.list(core.schemas.lazyObject(() => serializers.rules.fliptRule)),
    nextPageToken: core.schemas.string(),
    totalCount: core.schemas.number(),
  });

export declare namespace fliptRuleList {
  interface Raw {
    rules: serializers.rules.fliptRule.Raw[];
    nextPageToken: string;
    totalCount: number;
  }
}
