/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptRuleCreate: core.schemas.ObjectSchema<fliptRuleCreate.Raw, FliptApi.rules.fliptRuleCreate> =
  core.schemas.object({
    segmentKey: core.schemas.string(),
    rank: core.schemas.number(),
  });

export declare namespace fliptRuleCreate {
  interface Raw {
    segmentKey: string;
    rank: number;
  }
}
