/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const ruleList: core.schemas.ObjectSchema<ruleList.Raw, FliptApi.rules.ruleList> = core.schemas.object({
  rules: core.schemas.list(core.schemas.lazyObject(() => serializers.rules.rule)),
  nextPageToken: core.schemas.string(),
  totalCount: core.schemas.number(),
});

export declare namespace ruleList {
  interface Raw {
    rules: serializers.rules.rule.Raw[];
    nextPageToken: string;
    totalCount: number;
  }
}
