/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const RuleList: core.schemas.ObjectSchema<RuleList.Raw, FliptApi.RuleList> = core.schemas.object({
  rules: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Rule)),
  nextPageToken: core.schemas.string(),
  totalCount: core.schemas.number(),
});

export declare namespace RuleList {
  interface Raw {
    rules: serializers.Rule.Raw[];
    nextPageToken: string;
    totalCount: number;
  }
}
