/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const RuleOrder: core.schemas.ObjectSchema<RuleOrder.Raw, FliptApi.RuleOrder> = core.schemas.object({
  ruleIds: core.schemas.list(core.schemas.string()),
});

export declare namespace RuleOrder {
  interface Raw {
    ruleIds: string[];
  }
}
