/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const RuleCreateRequest: core.schemas.ObjectSchema<RuleCreateRequest.Raw, FliptApi.RuleCreateRequest> =
  core.schemas.object({
    segmentKey: core.schemas.string(),
    rank: core.schemas.number(),
  });

export declare namespace RuleCreateRequest {
  interface Raw {
    segmentKey: string;
    rank: number;
  }
}
