/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Rule: core.schemas.ObjectSchema<serializers.Rule.Raw, FliptApi.Rule> = core.schemas.object({
  id: core.schemas.string(),
  flagKey: core.schemas.string(),
  segmentKey: core.schemas.string(),
  distributions: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Distribution)),
  rank: core.schemas.number(),
  createdAt: core.schemas.date(),
  updatedAt: core.schemas.date(),
});

export declare namespace Rule {
  interface Raw {
    id: string;
    flagKey: string;
    segmentKey: string;
    distributions: serializers.Distribution.Raw[];
    rank: number;
    createdAt: string;
    updatedAt: string;
  }
}
