/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const RuleUpdateRequest: core.schemas.ObjectSchema<RuleUpdateRequest.Raw, FliptApi.RuleUpdateRequest> =
  core.schemas.object({
    segmentKey: core.schemas.string(),
  });

export declare namespace RuleUpdateRequest {
  interface Raw {
    segmentKey: string;
  }
}
