/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const rule: core.schemas.ObjectSchema<rule.Raw, FliptApi.rules.rule> = core.schemas.object({
  id: core.schemas.string(),
  flagKey: core.schemas.string(),
  segmentKey: core.schemas.string(),
  distributions: core.schemas.list(core.schemas.lazyObject(() => serializers.distributions.distribution)),
  rank: core.schemas.number(),
  createdAt: core.schemas.date(),
  updatedAt: core.schemas.date(),
});

export declare namespace rule {
  interface Raw {
    id: string;
    flagKey: string;
    segmentKey: string;
    distributions: serializers.distributions.distribution.Raw[];
    rank: number;
    createdAt: string;
    updatedAt: string;
  }
}
