/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const ruleCreateRequest: core.schemas.ObjectSchema<ruleCreateRequest.Raw, FliptApi.rules.ruleCreateRequest> =
  core.schemas.object({
    segmentKey: core.schemas.string(),
    rank: core.schemas.number(),
  });

export declare namespace ruleCreateRequest {
  interface Raw {
    segmentKey: string;
    rank: number;
  }
}
