/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const DistributionCreateRequest: core.schemas.ObjectSchema<
  DistributionCreateRequest.Raw,
  FliptApi.DistributionCreateRequest
> = core.schemas.object({
  variantId: core.schemas.string(),
  rollout: core.schemas.number(),
});

export declare namespace DistributionCreateRequest {
  interface Raw {
    variantId: string;
    rollout: number;
  }
}
