/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const DistributionUpdateRequest: core.schemas.ObjectSchema<
  DistributionUpdateRequest.Raw,
  FliptApi.DistributionUpdateRequest
> = core.schemas.object({
  variantId: core.schemas.string(),
  rollout: core.schemas.number(),
});

export declare namespace DistributionUpdateRequest {
  interface Raw {
    variantId: string;
    rollout: number;
  }
}
