/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Distribution: core.schemas.ObjectSchema<serializers.Distribution.Raw, FliptApi.Distribution> =
  core.schemas.object({
    id: core.schemas.string(),
    ruleId: core.schemas.string(),
    variantId: core.schemas.string(),
    rollout: core.schemas.number(),
    createdAt: core.schemas.date(),
    updatedAt: core.schemas.date(),
  });

export declare namespace Distribution {
  interface Raw {
    id: string;
    ruleId: string;
    variantId: string;
    rollout: number;
    createdAt: string;
    updatedAt: string;
  }
}
