/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const distributionCreateRequest: core.schemas.ObjectSchema<
  distributionCreateRequest.Raw,
  FliptApi.distributions.distributionCreateRequest
> = core.schemas.object({
  variantId: core.schemas.string(),
  rollout: core.schemas.number(),
});

export declare namespace distributionCreateRequest {
  interface Raw {
    variantId: string;
    rollout: number;
  }
}
