/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const distributionUpdateRequest: core.schemas.ObjectSchema<
  distributionUpdateRequest.Raw,
  FliptApi.distributions.distributionUpdateRequest
> = core.schemas.object({
  variantId: core.schemas.string(),
  rollout: core.schemas.number(),
});

export declare namespace distributionUpdateRequest {
  interface Raw {
    variantId: string;
    rollout: number;
  }
}
