/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptDistributionCreate: core.schemas.ObjectSchema<
  fliptDistributionCreate.Raw,
  FliptApi.distributions.fliptDistributionCreate
> = core.schemas.object({
  variantId: core.schemas.string(),
  rollout: core.schemas.number(),
});

export declare namespace fliptDistributionCreate {
  interface Raw {
    variantId: string;
    rollout: number;
  }
}
