/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptDistributionUpdate: core.schemas.ObjectSchema<
  fliptDistributionUpdate.Raw,
  FliptApi.distributions.fliptDistributionUpdate
> = core.schemas.object({
  variantId: core.schemas.string(),
  rollout: core.schemas.number(),
});

export declare namespace fliptDistributionUpdate {
  interface Raw {
    variantId: string;
    rollout: number;
  }
}
