/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface FlagCreateRequest {
    key: string;
    name: string;
    description?: string;
    enabled?: boolean;
    type: FliptApi.FlagType;
}
