/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FlagType = "VARIANT_FLAG_TYPE" | "BOOLEAN_FLAG_TYPE";

export const FlagType = {
    VariantFlagType: "VARIANT_FLAG_TYPE",
    BooleanFlagType: "BOOLEAN_FLAG_TYPE",
} as const;
