/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.segments.create.Request.Raw, FliptApi.SegmentCreateRequest> =
  core.schemas.object({
    key: core.schemas.string(),
    name: core.schemas.string(),
    description: core.schemas.string(),
    matchType: core.schemas.lazy(async () => (await import("../..")).SegmentMatchType),
  });

export declare namespace Request {
  interface Raw {
    key: string;
    name: string;
    description: string;
    matchType: serializers.SegmentMatchType.Raw;
  }
}

export const Response: core.schemas.Schema<serializers.segments.create.Response.Raw, FliptApi.Segment> =
  core.schemas.lazyObject(async () => (await import("../..")).Segment);

export declare namespace Response {
  type Raw = serializers.Segment.Raw;
}
