/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.segments.get.Response.Raw, FliptApi.Segment> =
  core.schemas.lazyObject(async () => (await import("../..")).Segment);

export declare namespace Response {
  type Raw = serializers.Segment.Raw;
}
