/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.segments.list.Response.Raw, FliptApi.SegmentList> =
  core.schemas.lazyObject(async () => (await import("../..")).SegmentList);

export declare namespace Response {
  type Raw = serializers.SegmentList.Raw;
}
