/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface SegmentCreateRequest {
    key: string;
    name: string;
    description: string;
    matchType: FliptApi.SegmentMatchType;
}
