/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const RolloutSegment: core.serialization.ObjectSchema<serializers.RolloutSegment.Raw, FliptApi.RolloutSegment> =
    core.serialization.object({
        segmentKey: core.serialization.string(),
        value: core.serialization.boolean(),
    });

export declare namespace RolloutSegment {
    interface Raw {
        segmentKey: string;
        value: boolean;
    }
}
