/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const RolloutOrderRequest: core.serialization.ObjectSchema<
    serializers.RolloutOrderRequest.Raw,
    FliptApi.RolloutOrderRequest
> = core.serialization.object({
    rolloutIds: core.serialization.list(core.serialization.string()),
});

export declare namespace RolloutOrderRequest {
    interface Raw {
        rolloutIds: string[];
    }
}
