/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.flags.create.Request.Raw, FliptApi.FlagCreateRequest> =
  core.schemas.object({
    key: core.schemas.string(),
    name: core.schemas.string(),
    description: core.schemas.string().optional(),
    enabled: core.schemas.boolean().optional(),
  });

export declare namespace Request {
  interface Raw {
    key: string;
    name: string;
    description?: string | null;
    enabled?: boolean | null;
  }
}

export const Response: core.schemas.Schema<serializers.flags.create.Response.Raw, FliptApi.Flag> =
  core.schemas.lazyObject(async () => (await import("../..")).Flag);

export declare namespace Response {
  type Raw = serializers.Flag.Raw;
}
