/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.flags.list.Response.Raw, FliptApi.FlagList> =
  core.schemas.lazyObject(async () => (await import("../..")).FlagList);

export declare namespace Response {
  type Raw = serializers.FlagList.Raw;
}
