/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface AuthenticationToken {
  clientToken: string;
  authentication: FliptApi.Authentication;
}
