/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface authenticationList extends FliptApi.commons.Pageable {
  authentications: FliptApi.auth.authentication[];
}
