/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";

/**
 * The default is METHOD_NONE
 */
export interface AuthenticationMethod<RawValue extends AuthenticationMethod.RawValue = AuthenticationMethod.RawValue> {
  value: RawValue;
  visit: <_Result>(visitor: FliptApi.AuthenticationMethod._Visitor<_Result>) => _Result;
}

const _MethodNone: AuthenticationMethod<"METHOD_NONE"> = {
  value: "METHOD_NONE",
  visit: (visitor) => visitor.methodNone(),
};
const _MethodToken: AuthenticationMethod<"METHOD_TOKEN"> = {
  value: "METHOD_TOKEN",
  visit: (visitor) => visitor.methodToken(),
};
export const AuthenticationMethod = {
  MethodNone: _MethodNone,
  MethodToken: _MethodToken,
  _parse: (value: string): AuthenticationMethod => {
    switch (value) {
      case "METHOD_NONE": {
        return _MethodNone;
      }
      case "METHOD_TOKEN": {
        return _MethodToken;
      }
      default: {
        return {
          value: value as AuthenticationMethod.RawValue,
          visit: (visitor) => visitor._other(value),
        };
      }
    }
  },
} as const;

export declare namespace AuthenticationMethod {
  type RawValue = "METHOD_NONE" | "METHOD_TOKEN";

  interface _Visitor<_Result> {
    methodNone: () => _Result;
    methodToken: () => _Result;
    _other: (value: string) => _Result;
  }
}
