/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";

export interface AuthenticationList {
  authentications: FliptApi.Authentication[];
  nextPageToken: string;
}
