/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthenticationTokenCreateRequest {
    name: string;
    namespaceKey?: string;
    description: string;
    expiresAt?: Date;
}
