/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FliptApi from "../../..";

export interface BatchEvaluationResponse {
    requestId: string;
    responses: FliptApi.EvaluationResponse[];
    requestDurationMillis: number;
}
