/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface EvaluationResponse {
    requestId: string;
    entityId: string;
    requestContext: Record<string, string | undefined>;
    match: boolean;
    flagKey: string;
    segmentKey: string;
    timestamp: Date;
    value: string;
    requestDurationMillis: number;
    attachment: string;
    reason: FliptApi.EvaluationReason;
    segmentKeys?: string;
}
