/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface fliptDistribution {
  id: string;
  ruleId: string;
  variantId: string;
  rollout: number;
  createdAt: Date;
  updatedAt: Date;
}
