/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.evaluate.evaluate.Request.Raw, FliptApi.EvaluationRequest> =
  core.schemas.lazyObject(async () => (await import("../..")).EvaluationRequest);

export declare namespace Request {
  type Raw = serializers.EvaluationRequest.Raw;
}

export const Response: core.schemas.Schema<serializers.evaluate.evaluate.Response.Raw, FliptApi.EvaluationResponse> =
  core.schemas.lazyObject(async () => (await import("../..")).EvaluationResponse);

export declare namespace Response {
  type Raw = serializers.EvaluationResponse.Raw;
}
