/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Request: core.schemas.Schema<
  serializers.auth.createToken.Request.Raw,
  FliptApi.AuthenticationTokenCreateRequest
> = core.schemas.object({
  name: core.schemas.string(),
  description: core.schemas.string(),
  expiresAt: core.schemas.date().optional(),
});

export declare namespace Request {
  interface Raw {
    name: string;
    description: string;
    expiresAt?: string | null;
  }
}

export const Response: core.schemas.Schema<serializers.auth.createToken.Response.Raw, FliptApi.AuthenticationToken> =
  core.schemas.lazyObject(async () => (await import("../..")).AuthenticationToken);

export declare namespace Response {
  type Raw = serializers.AuthenticationToken.Raw;
}
