/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptVariant: core.schemas.ObjectSchema<fliptVariant.Raw, FliptApi.variants.fliptVariant> =
  core.schemas.object({
    id: core.schemas.string(),
    flagKey: core.schemas.string(),
    key: core.schemas.string(),
    name: core.schemas.string(),
    description: core.schemas.string(),
    createdAt: core.schemas.date(),
    updatedAt: core.schemas.date(),
    attachment: core.schemas.string(),
  });

export declare namespace fliptVariant {
  interface Raw {
    id: string;
    flagKey: string;
    key: string;
    name: string;
    description: string;
    createdAt: string;
    updatedAt: string;
    attachment: string;
  }
}
