/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptVariantCreate: core.schemas.ObjectSchema<
  fliptVariantCreate.Raw,
  FliptApi.variants.fliptVariantCreate
> = core.schemas.object({
  key: core.schemas.string(),
  name: core.schemas.string().optional(),
  description: core.schemas.string().optional(),
  attachment: core.schemas.string().optional(),
});

export declare namespace fliptVariantCreate {
  interface Raw {
    key: string;
    name?: string | null;
    description?: string | null;
    attachment?: string | null;
  }
}
