/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const Variant: core.schemas.ObjectSchema<Variant.Raw, FliptApi.Variant> = core.schemas.object({
  id: core.schemas.string(),
  flagKey: core.schemas.string(),
  key: core.schemas.string(),
  name: core.schemas.string(),
  description: core.schemas.string(),
  createdAt: core.schemas.date(),
  updatedAt: core.schemas.date(),
  attachment: core.schemas.string(),
});

export declare namespace Variant {
  interface Raw {
    id: string;
    flagKey: string;
    key: string;
    name: string;
    description: string;
    createdAt: string;
    updatedAt: string;
    attachment: string;
  }
}
