/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const VariantCreateRequest: core.schemas.ObjectSchema<VariantCreateRequest.Raw, FliptApi.VariantCreateRequest> =
  core.schemas.object({
    key: core.schemas.string(),
    name: core.schemas.string().optional(),
    description: core.schemas.string().optional(),
    attachment: core.schemas.string().optional(),
  });

export declare namespace VariantCreateRequest {
  interface Raw {
    key: string;
    name?: string | null;
    description?: string | null;
    attachment?: string | null;
  }
}
