/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface constraint {
  id: string;
  segmentKey: string;
  type: FliptApi.constraints.constraintComparisonType;
  property: string;
  operator: string;
  value: string;
  createdAt: Date;
  updatedAt: Date;
}
