/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";

export interface ConstraintCreateRequest {
  type: FliptApi.ConstraintComparisonType;
  property: string;
  operator: string;
  value?: string;
}
