/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface constraintUpdateRequest {
  type: FliptApi.constraints.constraintComparisonType;
  property: string;
  operator: string;
  value?: string;
}
