/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface fliptConstraintUpdateRequest {
  type: FliptApi.commons.fliptComparisonType;
  property: string;
  operator: string;
  value?: string;
}
