/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Variant {
  id: string;
  flagKey: string;
  key: string;
  name: string;
  description: string;
  createdAt: Date;
  updatedAt: Date;
  attachment: string;
}
