/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../../core";

export const RuleUpdateRequest: core.serialization.Schema<
    serializers.RuleUpdateRequest.Raw,
    FliptApi.RuleUpdateRequest
> = core.serialization.object({
    segmentKey: core.serialization.string(),
});

export declare namespace RuleUpdateRequest {
    interface Raw {
        segmentKey: string;
    }
}
