/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { FliptApi } from "../../..";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      credentials?: core.Supplier<core.BasicAuth>;
    };
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async evaluate(
    request: FliptApi.evaluate.fliptEvaluationRequest
  ): Promise<FliptApi.evaluate.evaluate.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/evaluate"),
      method: "POST",
      headers: {
        Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options.auth?.credentials)),
      },
      body: serializers.evaluate.fliptEvaluationRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: serializers.evaluate.fliptEvaluationResponse.parse(
          response.body as serializers.evaluate.fliptEvaluationResponse.Raw
        ),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async batchEvaluate(
    request: FliptApi.evaluate.fliptBatchEvaluationRequest
  ): Promise<FliptApi.evaluate.batchEvaluate.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/batch-evaluate"),
      method: "POST",
      headers: {
        Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options.auth?.credentials)),
      },
      body: serializers.evaluate.fliptBatchEvaluationRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: serializers.evaluate.fliptBatchEvaluationResponse.parse(
          response.body as serializers.evaluate.fliptBatchEvaluationResponse.Raw
        ),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
