/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface fliptRule {
  id: string;
  flagKey: string;
  segmentKey: string;
  distributions: FliptApi.distributions.fliptDistribution[];
  rank: number;
  createdAt: Date;
  updatedAt: Date;
}
