/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface fliptRuleList {
  rules: FliptApi.rules.fliptRule[];
  nextPageToken: string;
  totalCount: number;
}
