/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";

export interface Rule {
  id: string;
  flagKey: string;
  segmentKey: string;
  distributions: FliptApi.Distribution[];
  rank: number;
  createdAt: Date;
  updatedAt: Date;
}
