/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface ruleList {
  rules: FliptApi.rules.rule[];
  nextPageToken: string;
  totalCount: number;
}
