/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptComparisonType: core.schemas.Schema<fliptComparisonType.Raw, FliptApi.commons.fliptComparisonType> =
  core.schemas.string().transform<FliptApi.commons.fliptComparisonType>({
    parse: (value) => FliptApi.commons.fliptComparisonType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace fliptComparisonType {
  type Raw = string;
}
