/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface SegmentList {
    segments: FliptApi.Segment[];
    nextPageToken: string;
    totalCount: number;
}
