/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SegmentMatchType = "ALL_MATCH_TYPE" | "ANY_MATCH_TYPE";

export const SegmentMatchType = {
    AllMatchType: "ALL_MATCH_TYPE",
    AnyMatchType: "ANY_MATCH_TYPE",
} as const;
