/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FliptApi from "../../..";

export interface SegmentList {
    segments: FliptApi.Segment[];
    nextPageToken: string;
    totalCount: number;
}
