/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface RolloutUpdateRequest {
    description?: string;
    segment?: FliptApi.RolloutSegment;
    threshold?: FliptApi.RolloutThreshold;
}
