/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface RolloutSegment {
    segmentKey: string;
    segmentKeys?: string[];
    segmentOperator?: FliptApi.RolloutSegmentOperator;
    value: boolean;
}
