/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface Rollout {
    id: string;
    namespaceKey: string;
    flagKey: string;
    type: FliptApi.RolloutType;
    rank: number;
    description: string;
    createdAt: Date;
    updatedAt: Date;
    segment?: FliptApi.RolloutSegment;
    threshold?: FliptApi.RolloutThreshold;
}
