/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FliptApi from "../../..";

export interface RolloutList {
    rollouts: FliptApi.Rollout[];
    nextPageToken: string;
    totalCount: number;
}
