/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FliptApi from "../../..";

export interface RolloutSegment {
    segmentKey: string;
    segmentKeys?: string[];
    segmentOperator?: FliptApi.RolloutSegmentOperator;
    value: boolean;
}
