/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptSegment: core.schemas.ObjectSchema<fliptSegment.Raw, FliptApi.segments.fliptSegment> =
  core.schemas.object({
    key: core.schemas.string(),
    name: core.schemas.string(),
    description: core.schemas.string(),
    createdAt: core.schemas.date(),
    updatedAt: core.schemas.date(),
    constraints: core.schemas.list(core.schemas.lazyObject(() => serializers.constraints.fliptConstraint)),
    matchType: core.schemas.lazy(() => serializers.segments.fliptMatchType),
  });

export declare namespace fliptSegment {
  interface Raw {
    key: string;
    name: string;
    description: string;
    createdAt: string;
    updatedAt: string;
    constraints: serializers.constraints.fliptConstraint.Raw[];
    matchType: serializers.segments.fliptMatchType.Raw;
  }
}
