/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptCreateSegmentRequest: core.schemas.ObjectSchema<
  fliptCreateSegmentRequest.Raw,
  FliptApi.segments.fliptCreateSegmentRequest
> = core.schemas.object({
  key: core.schemas.string(),
  name: core.schemas.string(),
  description: core.schemas.string(),
  matchType: core.schemas.lazy(() => serializers.segments.fliptMatchType),
});

export declare namespace fliptCreateSegmentRequest {
  interface Raw {
    key: string;
    name: string;
    description: string;
    matchType: serializers.segments.fliptMatchType.Raw;
  }
}
