/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptSegmentList: core.schemas.ObjectSchema<fliptSegmentList.Raw, FliptApi.segments.fliptSegmentList> =
  core.schemas
    .object({
      segments: core.schemas.list(core.schemas.lazyObject(() => serializers.segments.fliptSegment)),
    })
    .extend(core.schemas.lazyObject(() => serializers.commons.Pageable));

export declare namespace fliptSegmentList {
  interface Raw extends serializers.commons.Pageable.Raw {
    segments: serializers.segments.fliptSegment.Raw[];
  }
}
