/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptUpdateSegmentRequest: core.schemas.ObjectSchema<
  fliptUpdateSegmentRequest.Raw,
  FliptApi.segments.fliptUpdateSegmentRequest
> = core.schemas.object({
  name: core.schemas.string(),
  description: core.schemas.string(),
  matchType: core.schemas.lazy(() => serializers.segments.fliptMatchType),
});

export declare namespace fliptUpdateSegmentRequest {
  interface Raw {
    name: string;
    description: string;
    matchType: serializers.segments.fliptMatchType.Raw;
  }
}
