/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptMatchType: core.schemas.Schema<fliptMatchType.Raw, FliptApi.segments.fliptMatchType> = core.schemas
  .string()
  .transform<FliptApi.segments.fliptMatchType>({
    parse: (value) => FliptApi.segments.fliptMatchType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace fliptMatchType {
  type Raw = string;
}
