/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const segmentMatchType: core.schemas.Schema<segmentMatchType.Raw, FliptApi.segments.segmentMatchType> =
  core.schemas.string().transform<FliptApi.segments.segmentMatchType>({
    parse: (value) => FliptApi.segments.segmentMatchType._parse(value),
    json: ({ value }) => value,
  });

export declare namespace segmentMatchType {
  type Raw = string;
}
