/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const SegmentList: core.schemas.ObjectSchema<SegmentList.Raw, FliptApi.SegmentList> = core.schemas
  .object({
    segments: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Segment)),
  })
  .extend(core.schemas.lazyObject(async () => (await import("../..")).Pageable));

export declare namespace SegmentList {
  interface Raw extends serializers.Pageable.Raw {
    segments: serializers.Segment.Raw[];
  }
}
