/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const segment: core.schemas.ObjectSchema<segment.Raw, FliptApi.segments.segment> = core.schemas.object({
  key: core.schemas.string(),
  name: core.schemas.string(),
  description: core.schemas.string(),
  createdAt: core.schemas.date(),
  updatedAt: core.schemas.date(),
  constraints: core.schemas.list(core.schemas.lazyObject(() => serializers.constraints.constraint)),
  matchType: core.schemas.lazy(() => serializers.segments.segmentMatchType),
});

export declare namespace segment {
  interface Raw {
    key: string;
    name: string;
    description: string;
    createdAt: string;
    updatedAt: string;
    constraints: serializers.constraints.constraint.Raw[];
    matchType: serializers.segments.segmentMatchType.Raw;
  }
}
