/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Segment: core.schemas.ObjectSchema<serializers.Segment.Raw, FliptApi.Segment> = core.schemas.object({
  key: core.schemas.string(),
  name: core.schemas.string(),
  description: core.schemas.string(),
  createdAt: core.schemas.date(),
  updatedAt: core.schemas.date(),
  constraints: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Constraint)),
  matchType: core.schemas.lazy(async () => (await import("../..")).SegmentMatchType),
});

export declare namespace Segment {
  interface Raw {
    key: string;
    name: string;
    description: string;
    createdAt: string;
    updatedAt: string;
    constraints: serializers.Constraint.Raw[];
    matchType: serializers.SegmentMatchType.Raw;
  }
}
