/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const segmentList: core.schemas.ObjectSchema<segmentList.Raw, FliptApi.segments.segmentList> = core.schemas
  .object({
    segments: core.schemas.list(core.schemas.lazyObject(() => serializers.segments.segment)),
  })
  .extend(core.schemas.lazyObject(() => serializers.commons.Pageable));

export declare namespace segmentList {
  interface Raw extends serializers.commons.Pageable.Raw {
    segments: serializers.segments.segment.Raw[];
  }
}
