/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const SegmentUpdateRequest: core.schemas.ObjectSchema<SegmentUpdateRequest.Raw, FliptApi.SegmentUpdateRequest> =
  core.schemas.object({
    name: core.schemas.string(),
    description: core.schemas.string(),
    matchType: core.schemas.lazy(async () => (await import("../..")).SegmentMatchType),
  });

export declare namespace SegmentUpdateRequest {
  interface Raw {
    name: string;
    description: string;
    matchType: serializers.SegmentMatchType.Raw;
  }
}
