/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { FliptApi } from "@flipt-io/flipt";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async list(request?: FliptApi.SegmentListRequest): Promise<FliptApi.segments.list.Response> {
    const _queryParams = new URLSearchParams();
    if (request?.limit != null) {
      _queryParams.append("limit", request?.limit.toString());
    }

    if (request?.offset != null) {
      _queryParams.append("offset", request?.offset.toString());
    }

    if (request?.pageToken != null) {
      _queryParams.append("pageToken", request?.pageToken);
    }

    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/api/v1/segments"),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      queryParameters: _queryParams,
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.segments.list.Response.parse(_response.body as serializers.segments.list.Response.Raw),
      };
    }

    return {
      ok: false,
      error: FliptApi.segments.list.Error._unknown(_response.error),
    };
  }

  public async create(request: FliptApi.SegmentCreateRequest): Promise<FliptApi.segments.create.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, "/api/v1/segments"),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      body: await serializers.segments.create.Request.json({
        key: request.key,
        name: request.name,
        description: request.description,
        matchType: request.matchType,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.segments.create.Response.parse(
          _response.body as serializers.segments.create.Response.Raw
        ),
      };
    }

    return {
      ok: false,
      error: FliptApi.segments.create.Error._unknown(_response.error),
    };
  }

  public async get(key: string): Promise<FliptApi.segments.get.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, `/api/v1/segments/${key}`),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.segments.get.Response.parse(_response.body as serializers.segments.get.Response.Raw),
      };
    }

    return {
      ok: false,
      error: FliptApi.segments.get.Error._unknown(_response.error),
    };
  }

  public async delete(key: string): Promise<FliptApi.segments.delete.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, `/api/v1/segments/${key}`),
      method: "DELETE",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
    });
    if (_response.ok) {
      return {
        ok: true,
        body: undefined,
      };
    }

    return {
      ok: false,
      error: FliptApi.segments.delete.Error._unknown(_response.error),
    };
  }

  public async update(key: string, request: FliptApi.SegmentUpdateRequest): Promise<FliptApi.segments.update.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.Environment.Production, `/api/v1/segments/${key}`),
      method: "PUT",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      body: await serializers.segments.update.Request.json({
        name: request.name,
        description: request.description,
        matchType: request.matchType,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.segments.update.Response.parse(
          _response.body as serializers.segments.update.Response.Raw
        ),
      };
    }

    return {
      ok: false,
      error: FliptApi.segments.update.Error._unknown(_response.error),
    };
  }
}
