/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export type Response = core.APIResponse<FliptApi.SegmentList, FliptApi.segments.list.Error>;
export type Error = FliptApi.segments.list.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: FliptApi.segments.list.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  _unknown: (fetcherError: core.Fetcher.Error): FliptApi.segments.list.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<FliptApi.segments.list.Error._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: FliptApi.segments.list.Error._Unknown, visitor: FliptApi.segments.list.Error._Visitor<_Result>) {
      return FliptApi.segments.list.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: FliptApi.segments.list.Error,
    visitor: FliptApi.segments.list.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      default:
        return visitor._other(value as any);
    }
  },
} as const;
