/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const Namespace: core.serialization.ObjectSchema<serializers.Namespace.Raw, FliptApi.Namespace> =
    core.serialization.object({
        key: core.serialization.string(),
        name: core.serialization.string(),
        description: core.serialization.string(),
        protected: core.serialization.boolean(),
        createdAt: core.serialization.date(),
        updatedAt: core.serialization.date(),
    });

export declare namespace Namespace {
    interface Raw {
        key: string;
        name: string;
        description: string;
        protected: boolean;
        createdAt: string;
        updatedAt: string;
    }
}
