/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const Request: core.schemas.Schema<
  serializers.constraints.update.Request.Raw,
  FliptApi.ConstraintUpdateRequest
> = core.schemas.object({
  type: core.schemas.lazy(async () => (await import("../..")).ConstraintComparisonType),
  property: core.schemas.string(),
  operator: core.schemas.string(),
  value: core.schemas.string().optional(),
});

export declare namespace Request {
  interface Raw {
    type: serializers.ConstraintComparisonType.Raw;
    property: string;
    operator: string;
    value?: string | null;
  }
}
