/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const FlagType: core.serialization.Schema<serializers.FlagType.Raw, FliptApi.FlagType> =
    core.serialization.enum_(["VARIANT_FLAG_TYPE", "BOOLEAN_FLAG_TYPE"]);

export declare namespace FlagType {
    type Raw = "VARIANT_FLAG_TYPE" | "BOOLEAN_FLAG_TYPE";
}
