/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const FlagCreateRequest: core.serialization.ObjectSchema<
    serializers.FlagCreateRequest.Raw,
    FliptApi.FlagCreateRequest
> = core.serialization.object({
    key: core.serialization.string(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    enabled: core.serialization.boolean().optional(),
});

export declare namespace FlagCreateRequest {
    interface Raw {
        key: string;
        name: string;
        description?: string | null;
        enabled?: boolean | null;
    }
}
