/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const DistributionUpdateRequest: core.serialization.ObjectSchema<
    serializers.DistributionUpdateRequest.Raw,
    FliptApi.DistributionUpdateRequest
> = core.serialization.object({
    variantId: core.serialization.string(),
    rollout: core.serialization.number(),
});

export declare namespace DistributionUpdateRequest {
    interface Raw {
        variantId: string;
        rollout: number;
    }
}
