/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FliptApi from "../../..";

export interface AuthenticationList {
    authentications: FliptApi.Authentication[];
    nextPageToken: string;
}
