/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface fliptMatchType<RawValue extends fliptMatchType.RawValue = fliptMatchType.RawValue> {
  value: RawValue;
  visit: <Result>(visitor: fliptMatchType._Visitor<Result>) => Result;
}

const _AllMatchType: fliptMatchType<"ALL_MATCH_TYPE"> = {
  value: "ALL_MATCH_TYPE",
  visit: (visitor) => visitor.allMatchType(),
};
const _AnyMatchType: fliptMatchType<"ANY_MATCH_TYPE"> = {
  value: "ANY_MATCH_TYPE",
  visit: (visitor) => visitor.anyMatchType(),
};
export const fliptMatchType = {
  AllMatchType: _AllMatchType,
  AnyMatchType: _AnyMatchType,
  _parse: (value: string): fliptMatchType => {
    switch (value) {
      case "ALL_MATCH_TYPE": {
        return _AllMatchType;
      }
      case "ANY_MATCH_TYPE": {
        return _AnyMatchType;
      }
      default: {
        return {
          value: value as fliptMatchType.RawValue,
          visit: (visitor) => visitor._other(value),
        };
      }
    }
  },
} as const;

export declare namespace fliptMatchType {
  type RawValue = "ALL_MATCH_TYPE" | "ANY_MATCH_TYPE";

  interface _Visitor<Result> {
    allMatchType: () => Result;
    anyMatchType: () => Result;
    _other: (value: string) => Result;
  }
}
