/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface fliptUpdateSegmentRequest {
  name: string;
  description: string;
  matchType: FliptApi.segments.fliptMatchType;
}
