/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface fliptSegment {
  key: string;
  name: string;
  description: string;
  createdAt: Date;
  updatedAt: Date;
  constraints: FliptApi.constraints.fliptConstraint[];
  matchType: FliptApi.segments.fliptMatchType;
}
