/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface segmentList extends FliptApi.commons.Pageable {
  segments: FliptApi.segments.segment[];
}
