/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface segmentMatchType<RawValue extends segmentMatchType.RawValue = segmentMatchType.RawValue> {
  value: RawValue;
  visit: <_Result>(visitor: FliptApi.segments.segmentMatchType._Visitor<_Result>) => _Result;
}

const _AllMatchType: segmentMatchType<"ALL_MATCH_TYPE"> = {
  value: "ALL_MATCH_TYPE",
  visit: (visitor) => visitor.allMatchType(),
};
const _AnyMatchType: segmentMatchType<"ANY_MATCH_TYPE"> = {
  value: "ANY_MATCH_TYPE",
  visit: (visitor) => visitor.anyMatchType(),
};
export const segmentMatchType = {
  AllMatchType: _AllMatchType,
  AnyMatchType: _AnyMatchType,
  _parse: (value: string): segmentMatchType => {
    switch (value) {
      case "ALL_MATCH_TYPE": {
        return _AllMatchType;
      }
      case "ANY_MATCH_TYPE": {
        return _AnyMatchType;
      }
      default: {
        return {
          value: value as segmentMatchType.RawValue,
          visit: (visitor) => visitor._other(value),
        };
      }
    }
  },
} as const;

export declare namespace segmentMatchType {
  type RawValue = "ALL_MATCH_TYPE" | "ANY_MATCH_TYPE";

  interface _Visitor<_Result> {
    allMatchType: () => _Result;
    anyMatchType: () => _Result;
    _other: (value: string) => _Result;
  }
}
