/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface segmentCreateRequest {
  key: string;
  name: string;
  description: string;
  matchType: FliptApi.segments.segmentMatchType;
}
