/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";

export interface Segment {
  key: string;
  name: string;
  description: string;
  createdAt: Date;
  updatedAt: Date;
  constraints: FliptApi.Constraint[];
  matchType: FliptApi.SegmentMatchType;
}
