/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface batchEvaluationResponse {
  requestId: string;
  response: FliptApi.evaluate.evaluationResponse[];
  requestDurationMillis: number;
}
