/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";

export interface BatchEvaluationRequest {
  requestId?: string;
  requests: FliptApi.EvaluationRequest[];
  excludeNotFound?: boolean;
}
