/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface batchEvaluationRequest {
  requestId?: string;
  requests: FliptApi.evaluate.evaluationRequest[];
  excludeNotFound?: boolean;
}
