/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface evaluationResponse {
  requestId: string;
  entityId: string;
  requestContext: string;
  match: boolean;
  flagKey: string;
  segmentKey: string;
  timestamp: Date;
  value: string;
  requestDurationMillis: number;
  attachment: string;
  reasons: FliptApi.evaluate.evaluationReason;
}
