/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface fliptBatchEvaluationResponse {
  requestId: string;
  response: FliptApi.evaluate.fliptEvaluationResponse[];
  requestDurationMillis: number;
}
