/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Distribution {
    id: string;
    ruleId: string;
    variantId: string;
    rollout: number;
    createdAt: Date;
    updatedAt: Date;
}
