/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface flagList extends FliptApi.commons.Pageable {
  flags: FliptApi.flags.flag[];
}
