/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";

export interface fliptFlagList extends FliptApi.commons.Pageable {
  flags: FliptApi.flags.fliptFlag[];
}
