/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FliptApi from "../../..";

export interface RuleList {
    rules: FliptApi.Rule[];
    nextPageToken: string;
    totalCount: number;
}
