/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";

export interface RuleUpdateRequest {
    segmentKey: string;
    segmentKeys?: string[];
    segmentOperator?: FliptApi.RuleSegmentOperator;
}
