/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const Rule: core.serialization.ObjectSchema<serializers.Rule.Raw, FliptApi.Rule> = core.serialization.object({
    id: core.serialization.string(),
    flagKey: core.serialization.string(),
    segmentKey: core.serialization.string(),
    distributions: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).Distribution)
    ),
    rank: core.serialization.number(),
    createdAt: core.serialization.date(),
    updatedAt: core.serialization.date(),
});

export declare namespace Rule {
    interface Raw {
        id: string;
        flagKey: string;
        segmentKey: string;
        distributions: serializers.Distribution.Raw[];
        rank: number;
        createdAt: string;
        updatedAt: string;
    }
}
