/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const RuleOrderRequest: core.serialization.ObjectSchema<
    serializers.RuleOrderRequest.Raw,
    FliptApi.RuleOrderRequest
> = core.serialization.object({
    ruleIds: core.serialization.list(core.serialization.string()),
});

export declare namespace RuleOrderRequest {
    interface Raw {
        ruleIds: string[];
    }
}
