/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { FliptApi } from "@fern-api/flipt";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      token?: core.Supplier<core.BearerToken>;
    };
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async create(request: FliptApi.distributions.create.Request): Promise<FliptApi.distributions.create.Response> {
    const response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/api/v1/flags/${request.flagKey}/rules/${request.ruleId}/distributions/`
      ),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.auth?.token)),
      },
      body: await serializers.DistributionCreateRequest.json(request._body),
    });
    if (response.ok) {
      return {
        ok: true,
        body: await serializers.Distribution.parse(response.body as serializers.Distribution.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async delete(request: FliptApi.distributions.delete.Request): Promise<FliptApi.distributions.delete.Response> {
    const queryParameters = new URLSearchParams();
    queryParameters.append("variantId", request.variantId);
    const response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/api/v1/flags/${request.flagKey}/rules/${request.ruleId}/distributions/${request.id}`
      ),
      method: "DELETE",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.auth?.token)),
      },
      queryParameters: queryParameters,
    });
    if (response.ok) {
      return {
        ok: true,
        body: undefined,
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async update(request: FliptApi.distributions.update.Request): Promise<FliptApi.distributions.update.Response> {
    const response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/api/v1/flags/${request.flagKey}/rules/${request.ruleId}/distributions/${request.id}`
      ),
      method: "PUT",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.auth?.token)),
      },
      body: await serializers.DistributionUpdateRequest.json(request._body),
    });
    if (response.ok) {
      return {
        ok: true,
        body: await serializers.Distribution.parse(response.body as serializers.Distribution.Raw),
      };
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
