/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { FliptApi } from "@flipt-io/flipt";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.Environment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async create(
    flagKey: string,
    ruleId: string,
    request: FliptApi.DistributionCreateRequest
  ): Promise<FliptApi.distributions.create.Response> {
    const _response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/api/v1/flags/${flagKey}/rules/${ruleId}/distributions/`
      ),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      body: await serializers.distributions.create.Request.json({
        variantId: request.variantId,
        rollout: request.rollout,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.distributions.create.Response.parse(
          _response.body as serializers.distributions.create.Response.Raw
        ),
      };
    }

    return {
      ok: false,
      error: FliptApi.distributions.create.Error._unknown(_response.error),
    };
  }

  public async delete(
    flagKey: string,
    ruleId: string,
    id: string,
    request: FliptApi.DistributionDeleteRequest
  ): Promise<FliptApi.distributions.delete.Response> {
    const _queryParams = new URLSearchParams();
    _queryParams.append("variantId", request.variantId);
    const _response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/api/v1/flags/${flagKey}/rules/${ruleId}/distributions//${id}`
      ),
      method: "DELETE",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      queryParameters: _queryParams,
    });
    if (_response.ok) {
      return {
        ok: true,
        body: undefined,
      };
    }

    return {
      ok: false,
      error: FliptApi.distributions.delete.Error._unknown(_response.error),
    };
  }

  public async update(
    flagKey: string,
    ruleId: string,
    id: string,
    request: FliptApi.DistributionUpdateRequest
  ): Promise<FliptApi.distributions.update.Response> {
    const _response = await core.fetcher({
      url: urlJoin(
        this.options.environment ?? environments.Environment.Production,
        `/api/v1/flags/${flagKey}/rules/${ruleId}/distributions//${id}`
      ),
      method: "PUT",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      body: await serializers.distributions.update.Request.json({
        variantId: request.variantId,
        rollout: request.rollout,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.distributions.update.Response.parse(
          _response.body as serializers.distributions.update.Response.Raw
        ),
      };
    }

    return {
      ok: false,
      error: FliptApi.distributions.update.Error._unknown(_response.error),
    };
  }
}
