/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const authenticationMethod: core.schemas.Schema<authenticationMethod.Raw, FliptApi.auth.authenticationMethod> =
  core.schemas.string().transform<FliptApi.auth.authenticationMethod>({
    parse: (value) => FliptApi.auth.authenticationMethod._parse(value),
    json: ({ value }) => value,
  });

export declare namespace authenticationMethod {
  type Raw = string;
}
