/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const AuthenticationTokenCreateRequest: core.schemas.ObjectSchema<
  AuthenticationTokenCreateRequest.Raw,
  FliptApi.AuthenticationTokenCreateRequest
> = core.schemas.object({
  name: core.schemas.string(),
  description: core.schemas.string(),
  expiresAt: core.schemas.date().optional(),
});

export declare namespace AuthenticationTokenCreateRequest {
  interface Raw {
    name: string;
    description: string;
    expiresAt?: string | null;
  }
}
