/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const AuthenticationMethod: core.schemas.Schema<AuthenticationMethod.Raw, FliptApi.AuthenticationMethod> =
  core.schemas.string().transform<FliptApi.AuthenticationMethod>({
    parse: (value) => FliptApi.AuthenticationMethod._parse(value),
    json: ({ value }) => value,
  });

export declare namespace AuthenticationMethod {
  type Raw = string;
}
