/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const AuthenticationToken: core.schemas.ObjectSchema<AuthenticationToken.Raw, FliptApi.AuthenticationToken> =
  core.schemas.object({
    clientToken: core.schemas.string(),
  });

export declare namespace AuthenticationToken {
  interface Raw {
    clientToken: string;
  }
}
