/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const Authentication: core.schemas.ObjectSchema<Authentication.Raw, FliptApi.Authentication> =
  core.schemas.object({
    id: core.schemas.string(),
    method: core.schemas.lazy(async () => (await import("../..")).AuthenticationMethod),
    createdAt: core.schemas.date(),
    updatedAt: core.schemas.date(),
    expiresAt: core.schemas.date().optional(),
    metadata: core.schemas.record(core.schemas.string(), core.schemas.string()),
  });

export declare namespace Authentication {
  interface Raw {
    id: string;
    method: serializers.AuthenticationMethod.Raw;
    createdAt: string;
    updatedAt: string;
    expiresAt?: string | null;
    metadata: Record<string, string>;
  }
}
