/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const authenticationTokenCreateRequest: core.schemas.ObjectSchema<
  authenticationTokenCreateRequest.Raw,
  FliptApi.auth.authenticationTokenCreateRequest
> = core.schemas.object({
  name: core.schemas.string(),
  description: core.schemas.string(),
  expiresAt: core.schemas.date().optional(),
});

export declare namespace authenticationTokenCreateRequest {
  interface Raw {
    name: string;
    description: string;
    expiresAt?: string | null;
  }
}
