/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const AuthenticationList: core.schemas.ObjectSchema<
  serializers.AuthenticationList.Raw,
  FliptApi.AuthenticationList
> = core.schemas.object({
  authentications: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Authentication)),
  nextPageToken: core.schemas.string(),
});

export declare namespace AuthenticationList {
  interface Raw {
    authentications: serializers.Authentication.Raw[];
    nextPageToken: string;
  }
}
