/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const authenticationToken: core.schemas.ObjectSchema<
  authenticationToken.Raw,
  FliptApi.auth.authenticationToken
> = core.schemas.object({
  clientToken: core.schemas.string(),
});

export declare namespace authenticationToken {
  interface Raw {
    clientToken: string;
  }
}
