/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const authenticationList: core.schemas.ObjectSchema<authenticationList.Raw, FliptApi.auth.authenticationList> =
  core.schemas
    .object({
      authentications: core.schemas.list(core.schemas.lazyObject(() => serializers.auth.authentication)),
    })
    .extend(core.schemas.lazyObject(() => serializers.commons.Pageable));

export declare namespace authenticationList {
  interface Raw extends serializers.commons.Pageable.Raw {
    authentications: serializers.auth.authentication.Raw[];
  }
}
