/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const authentication: core.schemas.ObjectSchema<authentication.Raw, FliptApi.auth.authentication> =
  core.schemas.object({
    id: core.schemas.string(),
    method: core.schemas.lazy(() => serializers.auth.authenticationMethod),
    createdAt: core.schemas.date(),
    updatedAt: core.schemas.date(),
    expiresAt: core.schemas.date().optional(),
    metadata: core.schemas.record(core.schemas.string(), core.schemas.string()),
  });

export declare namespace authentication {
  interface Raw {
    id: string;
    method: serializers.auth.authenticationMethod.Raw;
    createdAt: string;
    updatedAt: string;
    expiresAt?: string | null;
    metadata: Record<string, string>;
  }
}
