/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const AuthenticationMethod: core.schemas.Schema<
  serializers.AuthenticationMethod.Raw,
  FliptApi.AuthenticationMethod
> = core.schemas.enum_(["METHOD_NONE", "METHOD_TOKEN", "METHOD_OIDC"]);

export declare namespace AuthenticationMethod {
  type Raw = "METHOD_NONE" | "METHOD_TOKEN" | "METHOD_OIDC";
}
