/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const AuthenticationList: core.schemas.ObjectSchema<AuthenticationList.Raw, FliptApi.AuthenticationList> =
  core.schemas
    .object({
      authentications: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).Authentication)),
    })
    .extend(core.schemas.lazyObject(async () => (await import("../..")).Pageable));

export declare namespace AuthenticationList {
  interface Raw extends serializers.Pageable.Raw {
    authentications: serializers.Authentication.Raw[];
  }
}
