/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { AuthMethodK8S } from "./api/resources/authMethodK8S/client/Client";
import { AuthMethodOidc } from "./api/resources/authMethodOidc/client/Client";
import { AuthMethodToken } from "./api/resources/authMethodToken/client/Client";
import { Auth } from "./api/resources/auth/client/Client";
import { Constraints } from "./api/resources/constraints/client/Client";
import { Distributions } from "./api/resources/distributions/client/Client";
import { Evaluate } from "./api/resources/evaluate/client/Client";
import { Flags } from "./api/resources/flags/client/Client";
import { Namespaces } from "./api/resources/namespaces/client/Client";
import { Rules } from "./api/resources/rules/client/Client";
import { Segments } from "./api/resources/segments/client/Client";
import { Variants } from "./api/resources/variants/client/Client";

export declare namespace FliptApiClient {
    interface Options {
        environment?: environments.FliptApiEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class FliptApiClient {
    constructor(private readonly options: FliptApiClient.Options) {}

    private _authMethodK8S: AuthMethodK8S | undefined;

    public get authMethodK8S(): AuthMethodK8S {
        return (this._authMethodK8S ??= new AuthMethodK8S(this.options));
    }

    private _authMethodOidc: AuthMethodOidc | undefined;

    public get authMethodOidc(): AuthMethodOidc {
        return (this._authMethodOidc ??= new AuthMethodOidc(this.options));
    }

    private _authMethodToken: AuthMethodToken | undefined;

    public get authMethodToken(): AuthMethodToken {
        return (this._authMethodToken ??= new AuthMethodToken(this.options));
    }

    private _auth: Auth | undefined;

    public get auth(): Auth {
        return (this._auth ??= new Auth(this.options));
    }

    private _constraints: Constraints | undefined;

    public get constraints(): Constraints {
        return (this._constraints ??= new Constraints(this.options));
    }

    private _distributions: Distributions | undefined;

    public get distributions(): Distributions {
        return (this._distributions ??= new Distributions(this.options));
    }

    private _evaluate: Evaluate | undefined;

    public get evaluate(): Evaluate {
        return (this._evaluate ??= new Evaluate(this.options));
    }

    private _flags: Flags | undefined;

    public get flags(): Flags {
        return (this._flags ??= new Flags(this.options));
    }

    private _namespaces: Namespaces | undefined;

    public get namespaces(): Namespaces {
        return (this._namespaces ??= new Namespaces(this.options));
    }

    private _rules: Rules | undefined;

    public get rules(): Rules {
        return (this._rules ??= new Rules(this.options));
    }

    private _segments: Segments | undefined;

    public get segments(): Segments {
        return (this._segments ??= new Segments(this.options));
    }

    private _variants: Variants | undefined;

    public get variants(): Variants {
        return (this._variants ??= new Variants(this.options));
    }
}
