/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const ConstraintComparisonType: core.schemas.Schema<
  serializers.ConstraintComparisonType.Raw,
  FliptApi.ConstraintComparisonType
> = core.schemas.enum_([
  "UNKNOWN_COMPARISON_TYPE",
  "STRING_COMPARISON_TYPE",
  "NUMBER_COMPARISON_TYPE",
  "BOOLEAN_COMPARISON_TYPE",
]);

export declare namespace ConstraintComparisonType {
  type Raw =
    | "UNKNOWN_COMPARISON_TYPE"
    | "STRING_COMPARISON_TYPE"
    | "NUMBER_COMPARISON_TYPE"
    | "BOOLEAN_COMPARISON_TYPE";
}
