/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const Constraint: core.schemas.ObjectSchema<Constraint.Raw, FliptApi.Constraint> = core.schemas.object({
  id: core.schemas.string(),
  segmentKey: core.schemas.string(),
  type: core.schemas.lazy(async () => (await import("../..")).ConstraintComparisonType),
  property: core.schemas.string(),
  operator: core.schemas.string(),
  value: core.schemas.string(),
  createdAt: core.schemas.date(),
  updatedAt: core.schemas.date(),
});

export declare namespace Constraint {
  interface Raw {
    id: string;
    segmentKey: string;
    type: serializers.ConstraintComparisonType.Raw;
    property: string;
    operator: string;
    value: string;
    createdAt: string;
    updatedAt: string;
  }
}
