/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const constraint: core.schemas.ObjectSchema<constraint.Raw, FliptApi.constraints.constraint> =
  core.schemas.object({
    id: core.schemas.string(),
    segmentKey: core.schemas.string(),
    type: core.schemas.lazy(() => serializers.constraints.constraintComparisonType),
    property: core.schemas.string(),
    operator: core.schemas.string(),
    value: core.schemas.string(),
    createdAt: core.schemas.date(),
    updatedAt: core.schemas.date(),
  });

export declare namespace constraint {
  interface Raw {
    id: string;
    segmentKey: string;
    type: serializers.constraints.constraintComparisonType.Raw;
    property: string;
    operator: string;
    value: string;
    createdAt: string;
    updatedAt: string;
  }
}
