/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const ConstraintCreateRequest: core.schemas.ObjectSchema<
  ConstraintCreateRequest.Raw,
  FliptApi.ConstraintCreateRequest
> = core.schemas.object({
  type: core.schemas.lazy(async () => (await import("../..")).ConstraintComparisonType),
  property: core.schemas.string(),
  operator: core.schemas.string(),
  value: core.schemas.string().optional(),
});

export declare namespace ConstraintCreateRequest {
  interface Raw {
    type: serializers.ConstraintComparisonType.Raw;
    property: string;
    operator: string;
    value?: string | null;
  }
}
