/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@fern-api/flipt";
import * as core from "../../../core";

export const ConstraintComparisonType: core.schemas.Schema<
  ConstraintComparisonType.Raw,
  FliptApi.ConstraintComparisonType
> = core.schemas.string().transform<FliptApi.ConstraintComparisonType>({
  parse: (value) => FliptApi.ConstraintComparisonType._parse(value),
  json: ({ value }) => value,
});

export declare namespace ConstraintComparisonType {
  type Raw = string;
}
