/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const constraintUpdateRequest: core.schemas.ObjectSchema<
  constraintUpdateRequest.Raw,
  FliptApi.constraints.constraintUpdateRequest
> = core.schemas.object({
  type: core.schemas.lazy(() => serializers.constraints.constraintComparisonType),
  property: core.schemas.string(),
  operator: core.schemas.string(),
  value: core.schemas.string().optional(),
});

export declare namespace constraintUpdateRequest {
  interface Raw {
    type: serializers.constraints.constraintComparisonType.Raw;
    property: string;
    operator: string;
    value?: string | null;
  }
}
