/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptConstraint: core.schemas.ObjectSchema<fliptConstraint.Raw, FliptApi.constraints.fliptConstraint> =
  core.schemas.object({
    id: core.schemas.string(),
    segmentKey: core.schemas.string(),
    type: core.schemas.lazy(() => serializers.commons.fliptComparisonType),
    property: core.schemas.string(),
    operator: core.schemas.string(),
    value: core.schemas.string(),
    createdAt: core.schemas.date(),
    updatedAt: core.schemas.date(),
  });

export declare namespace fliptConstraint {
  interface Raw {
    id: string;
    segmentKey: string;
    type: serializers.commons.fliptComparisonType.Raw;
    property: string;
    operator: string;
    value: string;
    createdAt: string;
    updatedAt: string;
  }
}
