/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";
import * as serializers from "../..";

export const BatchEvaluationResponse: core.schemas.ObjectSchema<
  BatchEvaluationResponse.Raw,
  FliptApi.BatchEvaluationResponse
> = core.schemas.object({
  requestId: core.schemas.string(),
  response: core.schemas.list(core.schemas.lazyObject(async () => (await import("../..")).EvaluationResponse)),
  requestDurationMillis: core.schemas.number(),
});

export declare namespace BatchEvaluationResponse {
  interface Raw {
    requestId: string;
    response: serializers.EvaluationResponse.Raw[];
    requestDurationMillis: number;
  }
}
