/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const batchEvaluationResponse: core.schemas.ObjectSchema<
  batchEvaluationResponse.Raw,
  FliptApi.evaluate.batchEvaluationResponse
> = core.schemas.object({
  requestId: core.schemas.string(),
  response: core.schemas.list(core.schemas.lazyObject(() => serializers.evaluate.evaluationResponse)),
  requestDurationMillis: core.schemas.number(),
});

export declare namespace batchEvaluationResponse {
  interface Raw {
    requestId: string;
    response: serializers.evaluate.evaluationResponse.Raw[];
    requestDurationMillis: number;
  }
}
