/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const batchEvaluationRequest: core.schemas.ObjectSchema<
  batchEvaluationRequest.Raw,
  FliptApi.evaluate.batchEvaluationRequest
> = core.schemas.object({
  requestId: core.schemas.string().optional(),
  requests: core.schemas.list(core.schemas.lazyObject(() => serializers.evaluate.evaluationRequest)),
  excludeNotFound: core.schemas.boolean().optional(),
});

export declare namespace batchEvaluationRequest {
  interface Raw {
    requestId?: string | null;
    requests: serializers.evaluate.evaluationRequest.Raw[];
    excludeNotFound?: boolean | null;
  }
}
