/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const EvaluationRequest: core.schemas.ObjectSchema<
  serializers.EvaluationRequest.Raw,
  FliptApi.EvaluationRequest
> = core.schemas.object({
  requestId: core.schemas.string().optional(),
  flagKey: core.schemas.string(),
  entityId: core.schemas.string(),
  context: core.schemas.record(core.schemas.string(), core.schemas.string()),
});

export declare namespace EvaluationRequest {
  interface Raw {
    requestId?: string | null;
    flagKey: string;
    entityId: string;
    context: Record<string, string>;
  }
}
