/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../core";

export const EvaluationRequest: core.schemas.ObjectSchema<EvaluationRequest.Raw, FliptApi.EvaluationRequest> =
  core.schemas.object({
    requestId: core.schemas.string().optional(),
    flagKey: core.schemas.string(),
    entityId: core.schemas.string(),
    context: core.schemas.string(),
  });

export declare namespace EvaluationRequest {
  interface Raw {
    requestId?: string | null;
    flagKey: string;
    entityId: string;
    context: string;
  }
}
