/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptEvaluationReason: core.schemas.Schema<
  fliptEvaluationReason.Raw,
  FliptApi.evaluate.fliptEvaluationReason
> = core.schemas.string().transform<FliptApi.evaluate.fliptEvaluationReason>({
  parse: (value) => FliptApi.evaluate.fliptEvaluationReason._parse(value),
  json: ({ value }) => value,
});

export declare namespace fliptEvaluationReason {
  type Raw = string;
}
