/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptBatchEvaluationRequest: core.schemas.ObjectSchema<
  fliptBatchEvaluationRequest.Raw,
  FliptApi.evaluate.fliptBatchEvaluationRequest
> = core.schemas.object({
  requestId: core.schemas.string().optional(),
  requests: core.schemas.list(core.schemas.lazyObject(() => serializers.evaluate.fliptEvaluationRequest)),
  excludeNotFound: core.schemas.boolean().optional(),
});

export declare namespace fliptBatchEvaluationRequest {
  interface Raw {
    requestId?: string | null;
    requests: serializers.evaluate.fliptEvaluationRequest.Raw[];
    excludeNotFound?: boolean | null;
  }
}
