/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const fliptBatchEvaluationResponse: core.schemas.ObjectSchema<
  fliptBatchEvaluationResponse.Raw,
  FliptApi.evaluate.fliptBatchEvaluationResponse
> = core.schemas.object({
  requestId: core.schemas.string(),
  response: core.schemas.list(core.schemas.lazyObject(() => serializers.evaluate.fliptEvaluationResponse)),
  requestDurationMillis: core.schemas.number(),
});

export declare namespace fliptBatchEvaluationResponse {
  interface Raw {
    requestId: string;
    response: serializers.evaluate.fliptEvaluationResponse.Raw[];
    requestDurationMillis: number;
  }
}
