/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FliptApi } from "../../..";
import * as core from "../../../core";

export const fliptEvaluationRequest: core.schemas.ObjectSchema<
  fliptEvaluationRequest.Raw,
  FliptApi.evaluate.fliptEvaluationRequest
> = core.schemas.object({
  requestId: core.schemas.string().optional(),
  flagKey: core.schemas.string(),
  entityId: core.schemas.string(),
  context: core.schemas.string(),
});

export declare namespace fliptEvaluationRequest {
  interface Raw {
    requestId?: string | null;
    flagKey: string;
    entityId: string;
    context: string;
  }
}
