/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Namespace {
    key: string;
    name: string;
    description: string;
    protected: boolean;
    createdAt: Date;
    updatedAt: Date;
}
