/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FliptApi } from "@flipt-io/flipt";
import * as core from "../../../../core";

export const Pageable: core.serialization.ObjectSchema<serializers.Pageable.Raw, FliptApi.Pageable> =
    core.serialization.object({
        nextPageToken: core.serialization.string().optional(),
        totalCount: core.serialization.number().optional(),
    });

export declare namespace Pageable {
    interface Raw {
        nextPageToken?: string | null;
        totalCount?: number | null;
    }
}
